global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - /etc/prometheus/rules/*

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "blackbox:tcp"
    metrics_path: /probe
    params:
      module: [tcp]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.json
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__address__, __port__]
        separator: ":"
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9115"

  - job_name: "blackbox:tls"
    metrics_path: /probe
    params:
      module: [tls]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.json
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__address__, __port__]
        separator: ":"
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "localhost:9115"
